### ISSUE TITLE
filters menu bugs

### ISSUE THREAD

**Issue by anuuyu** [stackbit/jamstackthemes#307]
there is a difference in the number of themes displayed
when on the homepage (https://jamstackthemes.dev/) 
![Screenshot from 2022-04-06 07-07-41](https://user-images.githubusercontent.com/6158924/161865381-0908451c-1485-4288-b56d-ca6dd84b3f52.png)

themes page (https://jamstackthemes.dev/theme/)
![Screenshot from 2022-04-06 07-06-33](https://user-images.githubusercontent.com/6158924/161865312-c81605fc-9748-4049-bf2c-af3b1f6446ce.png)

**Comment by JugglerX** [comment]
We only show filters that have 10 or more themes above the + toggle.

On the homepage there are less themes because we filter out stale (themes with no commits in 1 year) and disabled themes.

So on the homepage there is less than 10 vuepress themes and thus the filter is hidden.

Not sure if it's optimal UX but it's the current expected behaviour, and not a bug as such.

**Comment by anuuyu** [comment]
thank you for the explanation
